select *
from customer;

-- Q1. What is the total revenue generated by male vs. female customers
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating)::numeric, 2) as highest_review
from customer
group by item_purchased
Order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount), 2) as average_revenue
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
-- subscriber and non subscriber?
select subscription_status,
count(*) as total_customer,
round(avg(purchase_amount), 2) as avg_revenue, 
sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_revenue , total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discount applied?
select item_purchased,
round(100 * sum( Case when discount_applied = 'Yes' then 1 else 0 End)/count(*) , 2) as percentage_of_Discount
from customer
group by item_purchased
order by percentage_of_discount desc
limit 5;

--Q7. Segment customers into new, Returning, and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases <= 1 Then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	Else 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, count(*) as total_customer
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;


--Q9. Are customers who are repeat buyers ( more than 5 previous purchased) also likely to subscribe?
select subscription_status, count(*) as total_customer 
from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group
select age_group,
sum(purchase_amount)
from customer
group by age_group;